[package]
name = "petfall"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.23"
json = "0.12.4"
itertools = "0.10.1"
tempfile = "3.2.0"
ctrlc = "3.2.0"
